### ISSUE TITLE
editing .hbs file help

### ISSUE THREAD

**Issue by murdoc2211** [zutrinken/bleak#11]
Hi

I am a novice developer currently setting up a blog for my ecommerce business. 
I just need help in indexing the .hbs files like what is where, I am having a lot of trouble, inserting and editing code at the wrong places. I understand the process is too hectic, but if you could just give a brief summary as to basic locations to edit for post, homepage, navigation menu, adding footer content, changing the header/nav menu base colour, and more menial and trivial stuff. 

I would also like to add a twitter feed along side the already placed instagram instansive widget. 
I also wanted to know if i could customise a tile - when does it take an image? I created 2 test blogs, both had images in the content, but only has an image with the title in the tile on the home page. 
I wanted to just create a pure image tile with a link leading to another website, not one of the blog pages. 

Please please try to help me, I am trying to do a lot with very little or no knowledge of the coding structure. 

Thanks in Advance

Dhaval

**Comment by zutrinken** [comment]
Hi Dhaval,

you didn’t really choose a proper theme for doing some first steps. You can get a lot of info about the file structure and stuff at ghost official [documentation](http://themes.ghost.org). If you take a look into the files you’ll see that there’s a footer inside the `default.hbs`. Colors you have to change in `src/sass/style.scss` which brings you to the situation, that you need to know how to use npm, grunt and bower.

> I would also like to add a twitter feed along side the already placed instagram instansive widget. 

I really don’t know what you refer to, sorry!

> I also wanted to know if i could customize a tile - when does it take an image?

You can set a post image in the ghost backend. There’s that little gear icon beside the update/publish button over the editor. If you’ve set one it will be shown on the home page. Also if you make a post sticky it gets a dark style.

> I wanted to just create a pure image tile with a link leading to another website, not one of the blog pages.

That’s not possible with ghosts default functions.

> Please please try to help me, I am trying to do a lot with very little or no knowledge of the coding structure.

As I said, you really picked the wrong project to start learning. This isn’t anything I can help you right now.

best,
peter

**Comment by ManuelRauber** [comment]
@zutrinken 

> you didn’t really choose a proper theme for doing some first steps.

I wouldn't say so. Besides of grunt, your theme is more clean then a lot of others using tons and tons of plugins. It's a good base for starting, as I did. :)

**Comment by Jivebunny** [comment]
@zutrinken @murdoc2211 
I think murdoc is talking about a different Ghost theme named 'bleak' as well which I recently stumbled upon when looking for your theme...

https://www.npmjs.com/package/bleak

at least that thing has an 'instagram widget'.

I'm fairly certain actually... Anyways, thanks for an awesome theme zutrinken. <3

**Comment by zutrinken** [comment]
@Jivebunny thanks for the hint.

I guess this issue can be closed for now.
