### ISSUE TITLE
Integrating Google Custom Search

### ISSUE THREAD

**Issue by ManuelRauber** [zutrinken/bleak#12]
Hi Peter,

In my fork I added Google Custom Search to have a nice search possibility (see it in action at https://manuel-rauber.com).

The Commit for this is: https://github.com/ManuelRauber/bleak/commit/9f116d8fbc9f6e1266c39036cdc36bd9a7ad3e75

As you see, this would include some refactoring as well as a little Introduction to Google Custom Search. Do you think it's useful to integrate this in the "base" (original) bleak template? If yes, I would prepare a Pull Request for it.

Greetings

**Comment by zutrinken** [comment]
Already saw it, but if I'm honest, I'd prefer to wait for the ghost search feature instead of a third party implementation, even if your integration looks really solid. But thanks for your offer anyway!
