### ISSUE TITLE
positions are all wrong ++

### ISSUE THREAD

**Issue by RiKiaR** [zutrinken/bleak#13]
Hi 

I have installed all the dependencies so that i can run grunt and edit scss to customize my theme. 
All of this work perfectly well and I have done most of my customization already. 

But when i started adding content to see how my post would look i encounter some weird behavior. 

first of all the page number and navigation buttons appear right under the cover picture on top of my first row of posts. secondly the footer bar appear right under the first row of posts and on top of my second row. withe the rest of the post continue under the footer bar. all the post on on row have the same height as the the tallest one instead of tiling them self neatly. and lately my when hitting the menu button it does not show up. 

I have been very careful only to edit the style.css file within my theme directory but to my astonishment it all works perfectly when I downloaded a fresh them and loaded the new css over to it.

Because my css apparently works like it should in a fresh theme i assume it's not a problem with my custom scss.

I hope I have described my issues sufficiently and someone can help me with this issue because editing my scss and then copying the css over to a different theme is really slowing down my development.

Thank you in advance for any help! 
RikiaR

**Comment by zutrinken** [comment]
* Did you remove the custom jQuery code injection as described in the [README](https://github.com/zutrinken/bleak#bleak)?
* Do you have a live version where I can have a look?

**Comment by RiKiaR** [comment]
Hi 
Form what I can gather jQuery is only present on older implementations of Ghost (pre 0.7).
But i did have a look anyway in my code injection footer and it is at this moment empty.

Sadly I do not yet have a live site for you to take a look at. 
 
But since a fresh theme folder in the same ghost setup works with the alternated css without issue.
it's seem unlikely the fault lies in the Ghost setup and not within the theme... 

My only conscious difference between the two theme folders, one where its not working and the fresh on with impotent css is that I ran:

`npm install`
`bower install`
and
`grunt`

within the theme folder that has a broken layout. 

again thank you for your help.
