### ISSUE TITLE
header font overridden

### ISSUE THREAD

**Issue by XIAZY** [zutrinken/bleak#14]
Hi!
First, thank you for your excellent theme. I found a problem in changing the default font: the font of `header-name` is overridden by the font of `body`.
config of `header-name`:
<img width="1275" alt="2016-03-28 12 39 06" src="https://cloud.githubusercontent.com/assets/8736607/14066494/84484440-f47d-11e5-85cd-7ebf96055334.png">
config of `body`:
<img width="1280" alt="2016-03-28 12 42 30" src="https://cloud.githubusercontent.com/assets/8736607/14066519/0186316a-f47e-11e5-91d9-6285daaf6640.png">
font identification in actual webpage:
<img width="361" alt="2016-03-28 12 44 00" src="https://cloud.githubusercontent.com/assets/8736607/14066526/35589910-f47e-11e5-9cd4-c0a97d86f872.png">

Thank you!

**Comment by zutrinken** [comment]
yes, of course, since `.header-name` hasn't an own font-family declaration. So it makes totally sense that it gets the font property of `body`. Only `.header-name em` has an own declaration ... this is just for the post count on archive pages.

**Comment by XIAZY** [comment]
Thank you for your explanation. Is there any way to change the font for the actual title of the blog? Thank you.


Sent from Outlook Mobile






On Mon, Mar 28, 2016 at 11:31 AM -0700, "Amende" <notifications@github.com> wrote:





yes, of course, since `.header-name` hasn't an own font-family declaration. So it makes totally sense that it gets the font property of `body`. Only `.header-name em` has an own declaration ... this is just for the post count on archive pages.

---

**Comment by zutrinken** [comment]
Of course, just add some `font-family: 'your-font';` declaration to `.header-name` and it overwrites the `body` declaration. Not that complicated, right?!

**Comment by XIAZY** [comment]
Thank you! That works for me.

**Comment by XIAZY** [comment]
By the way, the programming style of `style.css` makes it very hard to make modifications, since all configs are condensed into one line. You may want to change the style in the future.

Again, thank you for your excellent theme. I really love it.

**Comment by zutrinken** [comment]
Well, please take a look at the Readme, there you find the development instructions. The CSS is build with SASS by [Grunt](http://gruntjs.com). So if you take a look at the `src` folder you find the `sass/style.scss` file which is used for development.

**Comment by XIAZY** [comment]
Oh, I see. Really sorry for the interruption and my foolishness.
