### ISSUE TITLE
Bower dependencies install

### ISSUE THREAD

**Issue by Tumetsu** [zutrinken/bleak#17]
When I installed this theme to Ghost's themes folder and ran development commands specified in readme `bower install` gave me error:
`ENOENT No bower.json present
`

After some bug-tracking it looks like that bower searches .bowerrc file and finds Ghost's in upper directory with following contents:
`{
    "cwd": "core/client/",
    "directory": "bower_components"
}
`
As you can see, this file sets cwd to core/client which leads bower install to fail in your theme folder which on build results dependencies not being concatenated to the `dependencies.js` asset. I solved the issue for now with adding the following .bowerrc file in the root of the theme:
`{
  "cwd": ".",
  "directory": "bower_components"
}
`

I thought to notify about this here since it confused me a lot. I guess one could solve the issue by adding symbolic link to the theme during the development but in any case, there probably should be a mention about the issue, or a .bowerrc file like I did.

Oh and very nice theme :)

**Comment by zutrinken** [comment]
Interesting and good to know. I'm not so experienced with bower but I guess the *.bowerrc* is only for system settings. so nothing that has to be part of the main project ... If I'm wrong, please make a PR. Thanks!
