### ISSUE TITLE
Hide Menubar Icon

### ISSUE THREAD

**Issue by merktassel** [zutrinken/bleak#19]
I just switched over to Ghost, and absolutely love this theme! However, since my website only has one page, there's no need for a navigation drawer. It'd be awesome if the navigation icon were hidden in cases like this.

**Comment by marc101101** [comment]
fork project kick it out by yourself :)

**Comment by gauderkd** [comment]
I dunno if you ended up solving this, but for anybody in the future either add .menu {display: none !important;} to style.css, or if you want to get rid of it entirely go to default.hbs and remove/comment out lines 35-37.

the RSS tag is there just above too if you don't want that either.

**Comment by zutrinken** [comment]
If your theme doesn't have a menu, the icon/menu want be shown. So this issue is kinda obsolete 🙃
