### ISSUE TITLE
no issue - feature request

### ISSUE THREAD

**Issue by leopoldkoch** [zutrinken/bleak#25]
First of all. Thanks! This is a great theme for Ghost you guys developed. I was looking for an option to show related articles on the article page itself. So you can keep the user engaged and on your page - any tipps on how to move forward on this? i would give it a try myself. Thanks and have a great day.

**Comment by zutrinken** [comment]
There are probably some workarounds like [jquery.ghostrelated](https://github.com/ljl/jquery.ghostrelated), but nothing served by default by ghost. So I don't think that this should be part of the main project and more like something everyone should care about individually.
