### ISSUE TITLE
Clicking the logo to go back to the blog home page opens it in a different context

### ISSUE THREAD

**Issue by Windyo** [zutrinken/bleak#27]
## Issue summary

Loading a ghost blog with the __bleak__ theme install via its URL (_e.g. http://www.my-ghost.blog.com_) and clicking on the blog logo on the top left do not have the exact same action.
## Issue dependencies

[GhostHunter](https://github.com/jamalneufeld/ghostHunter)
## Reproductibility steps
1. Install ghost from the latest master
2. Install Bleak from Github
3. Add Ghosthunter to the theme
4. Ghosthunter works when loading the main page, but fails when going back to the main page from a blog post. console.logs show the data is being queried but not displayed for some reason.
## Technical notes

Ghosthunter was grafted to the theme by adding files (search.js, search.css) in all places possible.
The only modifications to the theme were in default.hbs where links to the scripts and css were added, and in index.hbs where the "results" section was added.

A live link can be given via PM.

**Comment by zutrinken** [comment]
I'm not sure, but it seems to me, that you just have to reload the initializing script. If you take a look in bleaks [script.js](https://github.com/zutrinken/bleak/blob/master/src/js/script.js#L171) you can see, that all functions are reloaded on every page load because of the AJAX stuff.

**Comment by Windyo** [comment]
if you mean the initializing script for Ghosthunter, it is loaded on every page. This is actually why i'm stumped : everything should work, it just doesn't.

**Comment by Windyo** [comment]
@zutrinken I added the ghostHunter reload to that part of the script but still no dice.
 For some reason the script just refuses to execute when the main page is reloaded via AJAX. Do you have any ideas on this matter ?

Thanks
