### ISSUE TITLE
No transtion effect between pages

### ISSUE THREAD

**Issue by xitaht** [zutrinken/bleak#29]
Hi,

Firstly, thank you for your elegant themes, it is nice and clean.
Next, I want to talk about my problem.
Basically the problem I met is that there is no transition effect when loading between pages and I am not sure where the problem is. 
I have  also tried your another theme, `innocent` , which the transition effect works perfectly.
Additionally , I am running ghost v0.90 so there shouldn't be any jQuery issues according to [your readme](https://dev.ghost.org/no-more-jquery/)

Could you help me? I am new to this `coding` world

Thanks

**Comment by zutrinken** [comment]
Can you provide a link to your site, where it doesn't work properly?
