### ISSUE TITLE
Display post image in post

### ISSUE THREAD

**Issue by rapsli** [zutrinken/bleak#3]
The post image is currently only used on the homepage. Would it be possible to display the image on the post as well?

**Comment by DeanWhitehouse** [comment]
You can do it by modifying the `post.hbs` file; 

```
<section class="post-content">
    {{#if image}}
        <figure class="post-image">
            <img src="{{image}}" alt="" />
        </figure>
    {{/if}}
    {{content}}
 </section>
```

**Comment by zutrinken** [comment]
@DeanWhitehouse thanks for your help!

@rapsli did this help you? ... Actually I'm still not happy with the implementation on the blog and archive pages, why I left it away in posts for now. Also I'd argue it's totally enough to display images inside the article. But of course I can comprehend your issue.

**Comment by rapsli** [comment]
yep. I'll close this.

**Comment by julienfabre** [comment]
Allow me to re-open the subject, how would you proceed to display the post image the same way the cover_image is displayed on the homepage?
