### ISSUE TITLE
Https animation failed? My settings file:

### ISSUE THREAD

**Issue by qiershow2** [zutrinken/bleak#31]
Https animation failed? My nginx settings file:

    server {
	    listen       80;
		server_name  ~^(www\.)?(.+)\.com$;
        return 301 https://$host$request_uri;
	}
    server {
	    listen       443 ssl http2;
        server_name ~^(www\.)?(.+)\.com$;
        ssl_certificate /home/ssl/ofo2.crt;
        ssl_certificate_key /home/ssl/ofo2.key;
	    #rewrite ^/(.*) https://ofo2.com/$1 permanent;
	access_log  logs/ghost.access.log;

     location ^~ / {
	 proxy_pass http://localhost:2368/;
	 proxy_set_header   X-Real-IP $remote_addr;
	 proxy_set_header   Host      $http_host;
	 }

        #error_page  404              /404.html;
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

**Comment by viralis** [comment]
Hi there.
I'm not quite sure what exactly happened from your question "Https animation failed."
Can you provide more info like output from the Developers' Error Console?

**Comment by zutrinken** [comment]
hey @qiershow2 your report seems cryptic to me. Please provide clear information about what happens and how I can reproduce it. I close this issue for now, but feel free to provide more information and I'll have a look.
