### ISSUE TITLE
Searching feature ?

### ISSUE THREAD

**Issue by blackyzero** [zutrinken/bleak#35]
Hi Team,

Thanks for making a nice theme.

I'd like to request a searching feature for this theme, it would be great to have it that makes a lot of easy to search for the post or content.

Thanks a lot.

**Comment by zutrinken** [comment]
There is no official search feature by ghost so there's nothing to implement. There are third party solutions for that, but that's not part of the theme. As soon as ghost provides a search function it will be implemented.

**Comment by blackyzero** [comment]
yeah,i see.
also, i found this one, https://www.algolia.com/
not sure if it possible to integrate into ghost in future
