### ISSUE TITLE
Image hover glitch on Chrome

### ISSUE THREAD

**Issue by fralec** [zutrinken/bleak#38]
There is a small glitch when you hover a starred post.

<img width="61" alt="screen shot 2017-05-21 at 13 26 04" src="https://cloud.githubusercontent.com/assets/12753484/26283454/64f8055c-3e29-11e7-8feb-85f208975c4b.png">

This bug only happened with Chome, I tried to reproduce the bug with Firefox and Safari.

Chrome: 58.0.3029.110
OS: macOS 10.12.4

**Comment by PhoenixPeca** [comment]
Hi,

I believe this isn't a bug with bleak theme itself, but rather a rendering issue with chrome's internal processes. 😄

**Comment by zutrinken** [comment]
hey @fralec I'm on Chrome Version 61.x and OS 10.13.1 right now and can't reproduce it. I guess waiting has fixed that issue already?! Please reopen if it's still present for you. Thanks!
