### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by PhoenixPeca** [zutrinken/bleak#40]
Hi @zutrinken,

Thanks for this theme. I have seen some updates in the master branch but the last release was made almost 2 years ago. Is it safe to use the master branch commits in production or were still expecting more commits in the master branch for a future release? 😄

**Comment by zutrinken** [comment]
Waited for ghost v1. Now it's here an there is finally a new [release](https://github.com/zutrinken/bleak/releases)
