### ISSUE TITLE
Ported version for leafpub

### ISSUE THREAD

**Issue by squadramunter** [zutrinken/bleak#41]
Want a ported version for Leafpub https://www.leafpub.org/ 

It's really awesome you need only to change the extensions for the hbs file.

If you can port this that would be awesome!

Bleak for Leafpub!

**Comment by zutrinken** [comment]
hey @squadramunter I think I have enough fun maintaining this theme for ghost. If it's so easy you can probably do it on your own like [others](https://themes.gohugo.io/bleak/) did. Thanks!
