### ISSUE TITLE
If I can help :)

### ISSUE THREAD

**Issue by pascalandy** [zutrinken/bleak#43]
I'm the owner of [play-with-ghost](http://play-with-ghost.com/) and one big feature I'm working on is to showcase templates I enjoy like yours. 

Let me know if I can help you by hosting a staging environment of your Ghost project(s) or anything related of the backend of hosting Ghost.

Cheers!
[Pascal](https://twitter.com/askpascalandy/)

**Comment by squadramunter** [comment]
One question why is this a issue? and second why not contacting the person on his mail? rather than posting this random comment?

**Comment by pascalandy** [comment]
Like you @squadramunter I enjoy using Github to communicate. If offering help to host a project is offending to you, I guess more gratitude in your own life could resolve many problems.

**Comment by zutrinken** [comment]
@pascalandy Thanks for letting me know. Will keep it in Mind :)
