### ISSUE TITLE
RSS Style not working.

### ISSUE THREAD

**Issue by squadramunter** [zutrinken/bleak#44]
This XML file does not appear to have any style information associated with it. The document tree is shown below.

`<rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" version="2.0">`

Don't know why but when I look at that page in Chrome or Firefox this RSS style is not working properly.

Maybe it's text/xml?
But needs to be text/html?

**Comment by zutrinken** [comment]
Hey @squadramunter can you provide any more context? I'm not sure what this issue is about, what I should check or how the theme effects this. I close it for the now until it's reproducible. Thanks!
