### ISSUE TITLE
a little help?

### ISSUE THREAD

**Issue by systemroot** [zutrinken/bleak#45]
Hello,

Posts Cover photo seems to be too big and page takes some more time to load then a normal page.. 
(I mean posts cover in home page not post cover when you open a single post)

So if you have some time can you please tell me how to resize posts list at homepage ?!
ex for now horizontally posts can be just 3 so i'll like to add 4!

Thanks. And good work btw all what it needs i think post resize and some widgets around!

**Comment by zutrinken** [comment]
Hey,

First there is no image resize function in ghost yet. So you just have the original size.

To get a 4 column layout you can extend the [sass file](https://github.com/zutrinken/bleak/blob/master/src/sass/style.scss#L1234) with the code shown below or just add this to your __Blog Header__ in the __Code Injection__ section:

````
<style>
	@media only screen and (min-width: 80em) {
		.post-list .post {
			width: 24.90%
		}
	}
</style>
````

Hope that helps.

**Comment by systemroot** [comment]
it worked! Thank you
