### ISSUE TITLE
An unnecessary * in the Menu bar

### ISSUE THREAD

**Issue by S8Cloud** [zutrinken/bleak#46]
![image](https://user-images.githubusercontent.com/27051990/32141255-8dd1592c-bcb6-11e7-8ab8-cc3544304a90.png)

It seems that a `*` in the bottom of the menu bar is unnecessary. Maybe it should be removed.
Thank you.

**Comment by S8Cloud** [comment]
Seems replacing `li:before{margin-top:0.125em;content:'*'}` in the css file `style.css` will work.

**Comment by zutrinken** [comment]
thanks @S8Cloud for the hint!
