### ISSUE TITLE
[Question] Few pre-installation questions to the developer...

### ISSUE THREAD

**Issue by praveenscience** [zutrinken/bleak#52]
I really love this theme and it is awesome! This is the right theme I have been searching for. I have a few questions out here.

1. Is Google Analytics supported? Since this theme is fully powered by AJAX, I am kinda scared, if it breaks the GA - coz it works on normal page-load and not on AJAX right?
2. What if there are people who have browser that doesn't support AJAX for some reason? Is it possible to disable the AJAX load functionality alone or is there any graceful degradation?
3. I haven't seen any commenting in the demo. Can I integrate my existing Disqus comments? What would you prefer to be the best one?
4. I am using Ghost version 0.11.11. Will this theme work for this version?
5. What is your take on adding a search functionality?
6. Does it have a light box functionality?
7. I am using PrismJS for the code / syntax highlighting - so will that be an issue if I change it?

These are the questions I have so far. Would really planning to implement it for this new year. What say?

**Comment by MaskyS** [comment]
I'm using this theme and I'd like to answer these:

1. Works fine
2. Unless if they are using Lynx as their daily driver, this is not an issue.
3. Did you read the README?
4, Yes
5. I have tried but it's troublesome
6. No, but it should be easy to implement.
7. no issues.

Please do switch to bleak!

**Comment by praveenscience** [comment]
@MaskyS Thanks mate. Will have a try for sure... Thank you so much. You made my day.

**Comment by zutrinken** [comment]
thanks @MaskyS for answering these questions! Regarding the search functionality – I'll integrate it as soon as it's a ghost core feature.

**Comment by praveenscience** [comment]
@zutrinken It's not gonna be a Ghost feature any time soon. So do you have any other better suggestions and ideas?

**Comment by zutrinken** [comment]
I guess [ghostHunter](https://github.com/jamalneufeld/ghostHunter) is the tool for you. So far I haven't worked with it, but saw it in several themes. Maybe I'll add it at some point.

**Comment by praveenscience** [comment]
I am going to try it out now... And if it works well, I am going to implement in my high traffic site as well. Once everything looks good, shall I create a PR along with screenshots?

**Comment by praveenscience** [comment]
Hey, sorry, so what do you think about comments? Use the same old disqus?

**Comment by zutrinken** [comment]
I'm happy to see a PR if you can implement it nicely and maintainable. For comments disqus, yes.

**Comment by praveenscience** [comment]
I'll do it @zutrinken - Just working on it... Thanks.

**Comment by praveenscience** [comment]
@zutrinken This looks promising. Have a look: http://flarum.org/
