### ISSUE TITLE
Weird footer behavior

### ISSUE THREAD

**Issue by joolsmtw** [zutrinken/bleak#59]
First off, Bleak is a really nice template and I've absolutely loved working with it so far!

My problem is that one specific article kind of screws up the footer loading. It doesn't happen with any other article though. As seen with the live examples below, the footer is directly placed *over* the article, at the bottom of the screen, so that it hovers over the text.

Article it does not happen with, e.g.: http://www.anti-imperialism.ml/2018/06/11/uber-die-europaische-arbeiteraristokratie/

Article it does happen with: http://www.anti-imperialism.ml/2017/11/12/china-ddr/

Originally I thought it might have been a cache problem, but now I've seen it happening on several browsers and PCs as well.
Footer code injection is empty.

I use a lot of HTML that overrides Markup in the articles, because Markup was kind of hard to use for some of the layout stuff I needed, so I have to assume it has to do with the HTML in the article. I'm not sure, if it would be fruitful to post the raw text/code of the article here, though.

Thanks in advance, in either case!

**Comment by joolsmtw** [comment]
Wow, as per usual, after half a day of trying to find the issue and then opening an issue on Github, you find the problem just afterwards.

Indeed, it was HTML leftovers in the article (bunch of closing span tags without opening ones) that caused that behavior.

**Comment by zutrinken** [comment]
I like these kind of issues :D ... glad you enjoy the theme. Have a nice day!
