### ISSUE TITLE
Spacing Disqus

### ISSUE THREAD

**Issue by dasbillgh** [zutrinken/bleak#6]
Hello,

when i added <script>var disqus="YOUR_DISQUS_SHORTNAME";</script> to my
Blog the spacing is too large.

Can you fix it or post a workaround?

**Comment by zutrinken** [comment]
Can you make a screenshot to demonstrate your shortcomings?

**Comment by dasbillgh** [comment]
![snap](https://cloud.githubusercontent.com/assets/12262208/12373869/0abd9754-bc8a-11e5-8e43-ea91d1d0932b.png)
