### ISSUE TITLE
Feature - add linkedin link

### ISSUE THREAD

**Issue by texano00** [zutrinken/bleak#62]
Can we add the Linkedin link on the user profile?

**Comment by texano00** [comment]
I've opened #63 but this is not enough.
We also need to add Linkedin input on the Ghost admin (under Social accounts).

**Comment by zutrinken** [comment]
Hey! That's definitely not on the theme side. As long as it's not in the ghost core I won't add any social link to the theme. As soon ghost adds linkedin to the core I'm happy for a full PR. Thanks!

**Comment by texano00** [comment]
@zutrinken i agree with you.
Thanks!
