### ISSUE TITLE
lightbox

### ISSUE THREAD

**Issue by msilight** [zutrinken/bleak#71]
Hello
Is there any way to add a lightbox to this them? I tried 3-4 different lightboxes,
none of them works.

**Comment by zutrinken** [comment]
The issue is, that light boxes usually expect to have the image wrapped by a link to the main image. So if you integrate one, you should handle the extra link in addition for each image via JS, since Ghost doesn't do this at the moment. Nothing theme wise.

**Comment by msilight** [comment]
No problem about linking, I do that with a js, problem was reloading the js in the theme.

**Comment by msilight** [comment]
Thanks

**Comment by zutrinken** [comment]
Ah okay, than you have to add your function to the [reload function](https://github.com/zutrinken/bleak/blob/master/src/js/script.js#L148-L155).
