### ISSUE TITLE
Problem in installing 

### ISSUE THREAD

**Issue by bhawnagusain6** [zutrinken/bleak#73]
I don't know why it's showing this when I am uploading themes

<img width="728" alt="Screenshot 2021-01-08 161756" src="https://user-images.githubusercontent.com/74604130/104007010-486a3e80-51cd-11eb-8326-d0597fab90b6.png">

**Comment by zutrinken** [comment]
I think you mix up Hugo and Ghost. The original theme here is made for Ghost, there's another fork for Hugo (not by me). Maybe you start with this.

**Comment by bhawnagusain6** [comment]
Could you please help me with this and send me zip file here

**Comment by zutrinken** [comment]
Are you working on Ghost or Hugo?

For Hugo ask you question in the [Hugo Repo](https://github.com/nayibor/hugo-theme-bleak-port)
For Ghost use the latest release of this [Repo](https://github.com/zutrinken/bleak/releases)

**Comment by bhawnagusain6** [comment]
I don't know what these are

**Comment by bhawnagusain6** [comment]
It is keep showing with all the the themes
The theme is missing the style.css stylesheet.

**Comment by zutrinken** [comment]
If you're unsure whether you're using Ghost or Hugo I can't help

**Comment by bhawnagusain6** [comment]
Can you suggest any best paid blog theme
