### ISSUE TITLE
Changing background colour

### ISSUE THREAD

**Issue by joachimBrindeau** [zutrinken/bleak#79]
Hello,

I really like your them but could you please give me a hand?

I'm trying to replace the light gray background everywhere on my website [dreets](https://dreets.fr) with another color (#B7CEC4) but don't know where to begin.
I tried the CSS I found online to no avail.

Thank you for your help.
Joachim

**Comment by zutrinken** [comment]
Hey! Happy to see you using it! You have to add the following to your code injection settings:
````HTML
<style>
  #wrapper {
    background: #B7CEC4;
  }
</style>
````
