### ISSUE TITLE
Flattr Code Injection

### ISSUE THREAD

**Issue by gummipunkt** [zutrinken/bleak#8]
Hey Peter,

awesome job, thank you so much! 

Perhaps you have time: I wish a Flattr Button with Code Injection like the Disqus-thing.

Thanks

**Comment by zutrinken** [comment]
Flattr? Seriously? After all their big fuckup with money back transfers? Even if I avoid the political perspective on that issue 😇 I think there is no broader need by more users. So forgive me when I advise you to do this in your own fork. 😬

best,
peter
